### ISSUE TITLE
Getting error after adding sdk in android kotlin project

### ISSUE THREAD

**Issue by grvsingh44** [Instamojo/instamojo-android-sdk#107]
Getting Error after adding instamojo sdk to kotlin project.

![Screenshot 2023-01-26 at 1 13 48 AM](https://user-images.githubusercontent.com/9382146/214671760-555bddd0-2d78-4bad-8358-b3ae34d63dcd.png)

any one can help on this. Please do let me know

**Comment by adesh-im** [comment]
Hi @grvsingh44 

Please see https://github.com/Instamojo/instamojo-android-sdk/issues/106#issuecomment-1380031031
Let us know if this helps.
