### ISSUE TITLE
instamojo with react-native

### ISSUE THREAD

**Issue by Manoj002** [Instamojo/instamojo-android-sdk#34]
hello people,
is there any way to integrate instamojo in react native, i know i can use nodejs library or nodejs to do so but i want to do it in pure react native...

any help will be highly appreciated!

**Comment by beyondinfinity01** [comment]
yeah it can be done ,
 https://medium.com/@sajanthomas01/integrate-instamojo-payment-gateway-in-react-native-app-973aeb2b9936
