### ISSUE TITLE
Instamojo payment activity fails to init even after passing correct Order ID!

### ISSUE THREAD

**Issue by amannirala13** [Instamojo/instamojo-android-sdk#78]
Instamojo payment screen fails to build even after passing the correct order ID. The Order IDs generate **works in the web URL** but when I try to initialize the inbuilt Payment Activity of Instamojo, it instantly calls the on **onInitiatePaymentFailure()** with the error message **_"Error in getting order data."_** I am sure that I followed all the step mentioned in the read me about how to integrate the API correctly. (The app even has got all required permissions)

**Comment by jashangoraya** [comment]
same problem for me 
PaymentDetailsActivity: Error: {
        "success": false,
        "message": "Not found."
    }

**Comment by rajjannu8125** [comment]
i am also getting the same error in my app
anybody get any solution for that above issue

**Comment by amannirala13** [comment]
@rajjannu8125  what is the error message you are experiencing?

**Comment by rajjannu8125** [comment]
> @rajjannu8125 what is the error message you are experiencing?

same problem for me
PaymentDetailsActivity: Error: {
"success": false,
"message": "Not found."
}

**Comment by adraj** [comment]
Same with me with success page not come after UPI ID successful payment i face issue from 1.5 month but not get solution yet.So i migrate to other payment gateway

**### I hope Instamojo give me Solution so i can use for other client** 


@amannirala13

**Comment by nshiva000** [comment]
same problem  getting error : PaymentDetailsActivity: Error: {
"success": false,
"message": "Not found."
} 
 do any one found the solution

**Comment by nshiva000** [comment]
Issue is solved for me.
Problem is with the invalid orderId 

> (check whether **order id** of length is 36 characters)

**Comment by Mani1124** [comment]
Same issue here

**Comment by amannirala13** [comment]
@Mani1124 

Please check [**this solution**](https://github.com/Instamojo/instamojo-android-sdk/issues/78#issuecomment-602171698) and if it solves your issue.

**Comment by nishant304** [comment]
> Issue is solved for me.
> Problem is with the invalid orderId
> 
> > (check whether **order id** of length is 36 characters)

Yes, that response comes with empty order id, maybe invalid order id.No changes are required on SDK end.

**Comment by anujdeo** [comment]
Same issue - Initiating Payment Failed. Error Fetching Order Details.

Error: {
        "success": false,
        "message": "Not found."
    }

I get 32 digit order ID from backend server and its valid. If I append it to my payment link in browser, it works properly.

**Comment by anujdeo** [comment]
> Instamojo payment screen fails to build even after passing the correct order ID. The Order IDs generate **works in the web URL** but when I try to initialize the inbuilt Payment Activity of Instamojo, it instantly calls the on **onInitiatePaymentFailure()** with the error message **_"Error in getting order data."_** I am sure that I followed all the step mentioned in the read me about how to integrate the API correctly. (The app even has got all required permissions)

Any luck? Did you solved this issue?

**Comment by amannirala13** [comment]
[This](https://github.com/Instamojo/instamojo-android-sdk/issues/78#issuecomment-602171698) solved my issue...

**Comment by anujdeo** [comment]
> [This](https://github.com/Instamojo/instamojo-android-sdk/issues/78#issuecomment-602171698) solved my issue...

What exactly you done? I am getting 32 digit valid order ID. But still it fails to initialize payment screen and gives me that error.
Please help me out, can you please share code snippet? This is very urgent for me. If possible send me your code for Generating order id & initiating payment on deo.anujgmail.com

**Comment by manojbhoir28** [comment]
> > [This](https://github.com/Instamojo/instamojo-android-sdk/issues/78#issuecomment-602171698) solved my issue...
> 
> What exactly you done? I am getting 32 digit valid order ID. But still it fails to initialize payment screen and gives me that error.
> Please help me out, can you please share code snippet? This is very urgent for me. If possible send me your code for Generating order id & initiating payment on deo.anujgmail.com

After doing some analysis I found that First you need to create Order using endpoint "**/v2/gateway/orders/**" this will give you 32 digit order id.

_See this Example Response :_
`
{
    "order": {
        "id": "d450ccc5ec474a3aaa9a7d2610cacbc5",
        "transaction_id": "9e69c720-9a70-4d56-8cd6-622e4b6e83a4",
        "status": "pending",
        "currency": "INR",
        "amount": "9.00",
        "name": "ABCD",
        "email": "foo@example.com",
        "phone": "+919969156561",
        "description": "Test description",
        "redirect_url": "https://swaggerhub.com/api/saich/pay-with-instamojo/1.0.0",
        "webhook_url": null,
        "created_at": "2021-07-30T05:32:41.024189Z",
        "resource_uri": "https://test.instamojo.com/v2/gateway/orders/id:d450ccc5ec474a3aaa9a7d2610cacbc5/",
        "customer_id": null
    },
    "payment_options": {
        "payment_url": "https://test.instamojo.com/@kasautiii/d450ccc5ec474a3aaa9a7d2610cacbc5?embed=form"
    }
}`

Now you have to create payment order for that order id using endpoint "**/v2/gateway/orders/payment-request/**" and pass 32 digit order id as request body here so you will get 36 digit payment order id which you have to pass in your android SDK and this will resolve your issue.

_Sample request for 2nd endpoint (Payment Order)_

`{
     "id": "d450ccc5ec474a3aaa9a7d2610cacbc5"
}`

_Sample response for 2nd endpoint (Payment Order)_

`{
    "order_id": "ce704eb9-0ba7-4d1d-93a7-d71633d63797",
    "name": "ABCD",
    "email": "foo@example.com",
    "phone": "+919969156561",
    "amount": "9.00"
}`

I don't know why they created this so complicated but it is working for me.
