### ISSUE TITLE
Unable to download 3.4.0 built

### ISSUE THREAD

**Issue by maheshnathwani** [Instamojo/instamojo-android-sdk#88]
Hi, I am not able to download the latest built i.e. 3.4.0 but was able to download the previous built 3.3.0. 

<img width="883" alt="lALPGojJ9QlBHGHMos0G5g_1766_162" src="https://user-images.githubusercontent.com/10951432/90380887-44ad1280-e09a-11ea-9861-c9d9879de06c.png">

**Comment by nishant304** [comment]
This should be fixed now
